dreamshaper/src/constants.ts

feat: update contract source id

---

3d-animation/README.md
3d-animation/src/3d-animation.ts

Feat#18 automatic setup for 3d animation style script

---

README-3d-animation.md
README-vits.md

feat: update loop configuration to restart on failure in installation notes

---

config.json
src/index.ts
src/interfaces.ts
src/queries.ts
src/worker.cjs
src/worker.ts

Fix#37 generic script issues and improvements

---

config.json
src/interfaces.ts
src/worker.cjs
src/worker.ts

Feat#36 add seed to tags

---

src/constants.ts
src/worker.cjs
src/worker.ts

feat: update nfts contract id and init state

---

config.json
src/worker.cjs
src/worker.ts

Feat#40 override of settings not working

---

src/constants.ts
src/worker.cjs
src/worker.ts

feat: implement overriding asset name if "Asset-Names" tag is sent in request tags

---

src/constants.ts
src/worker.cjs
src/worker.ts

Feat#46 random hash in asset name

---

src/constants.ts
src/index.ts
src/interfaces.ts
src/queries.ts
src/worker.cjs
src/worker.ts

feat: update tags used in uploads

---

src/constants.ts
src/worker.cjs
src/worker.ts

feat: add functionality to use user passeed tags to the generated content

---

src/worker.cjs
src/worker.ts

feat: change responses tags order

---

src/worker.cjs
src/worker.ts

fix: adding custom tags mantaining order

---

src/constants.ts
src/index.ts
src/queries.ts
src/worker.cjs
src/worker.ts

Feat#50 choose images per prompts on scripts

---

src/constants.ts
src/queries.ts
src/worker.cjs
src/worker.ts

feat: update txs tags and queries to use protocol name

---

src/test-inference.ts

feat: add test-inference script

---

src/constants.ts
src/worker.cjs
src/worker.ts

feat: add logic to skip creating atomic assets

---

package-lock.json
package.json
src/constants.ts
src/worker.cjs
src/worker.ts

Closes #90 
ALso changes default assets balance to 1000

Feat#90 allow license configuration for responses

---

src/worker.cjs
src/worker.ts

fix: protect inference when fetching request data fails

---

config.json
src/index.ts
src/worker.cjs

Feat#100 operator proofs

---

src/worker.cjs

feat: if init-State is passed in custom tags replace creator and script User tags with firstOwner value

---

config.json
generic-script/variants/mixtral/README.md
src/interfaces.ts
src/worker.cjs

Feat#106 text to text model support

---

src/worker.cjs

feat: allow overriding image sizes

---

generic-script/variants/animics-v12/config.json

feat: update negative prompt config
